services:
  db:
    image: postgres:15
    container_name: elecciones-db
    environment:
      POSTGRES_USER: alfredo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sistema_elecciones
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: